<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('users')->insert([
            [
                'id' => 5031,
                'empid' => '2007-220',
                'fname' => 'Lannie May',
                'mname' => 'Espiritu',
                'lname' => 'Santos',
                'extension' => 'N/A',
                'fullname' => 'Lannie May Espiritu Santos',
                'maiden_name' => 'N/A',
                'birthday' => null,
                'birthplace' => 'N/A',
                'citizenship' => 'N/A',
                'citizenship_type' => 'N/A',
                'citizenship_country' => 'N/A',
                'gender' => null,
                'tribe' => null,
                'marital_status' => 'N/A',
                'other_status' => 'N/A',
                'religion' => null,
                'disability' => null,
                'specialization' => null,
                'height' => 'N/A',
                'weight' => 'N/A',
                'bloodtype' => 'N/A',
                'gsis_id' => 'N/A',
                'umid_id' => 'N/A',
                'pagibig_id' => 'N/A',
                'philhealth_id' => 'N/A',
                'sss_id' => 'N/A',
                'philsys_id' => 'N/A',
                'tin_no' => 'N/A',
                'agency_emp_no' => 'N/A',
                'add1_lot_no' => 'N/A',
                'add1_street' => 'N/A',
                'add1_sub' => 'N/A',
                'add1_brgy' => 'N/A',
                'add1_city' => 'N/A',
                'add1_prov' => 'N/A',
                'add1_zip' => 'N/A',
                'add2_lot_no' => 'N/A',
                'add2_street' => 'N/A',
                'add2_sub' => 'N/A',
                'add2_brgy' => 'N/A',
                'add2_city' => 'N/A',
                'add2_prov' => 'N/A',
                'add2_zip' => 'N/A',
                'tel_no' => 'N/A',
                'contact' => 'N/A',
                'slug' => null,
                'email' => 'Lannie@gmail.com',
                'password' => '$2y$10$.EdPFiCTdyQcp8OBDrgzGOQPCZ2B4enNkN5qgfO8Rofq6oIRdrhI.',
                'areacode' => 'IFSU 101',
                'academic_rank' => 'Associate Profesor I',
                'hep' => 'N/A',
                'hep_course' => null,
                'hep_units' => null,
                'user_access' => null,
                'user_data_man_role' => '4',
                'sias_role' => null,
                'user_role' => '2',
                'user_hr_role' => null,
                'user_dept_role' => null,
                'user_data_role' => null,
                'department' => 16,
                'college' => null,
                'position' => null,
                'parentethical_id' => null,
                'emp_cat' => null,
                'r_status' => null,
                'deactivation_reason' => null,
                'is_approved' => null,
                'validator_comment' => null,
                'account_id' => null,
                'is_admin' => null,
                'user_journal_role' => null,
                'remember_token' => null,
                'created_at' => '2026-03-25 00:14:18',
                'updated_at' => '2026-04-10 03:11:41',
                'deleted_at' => null,
                'activated_at' => null,
                'last_login' => null,
                'verification_code' => null,
                'verification_created_at' => null,
                'is_requested_vrc' => 'N',
                'password_reset_at' => null,
                'created_user_id' => null,
                'deleted_user_id' => null,
                'activated_user_id' => null,
                'is_project_based' => 'N',
            ],
            [
                'id' => 5053,
                'empid' => 'N/A',
                'fname' => 'Admin',
                'mname' => 'N/A',
                'lname' => 'User',
                'extension' => 'N/A',
                'fullname' => 'Admin User',
                'maiden_name' => 'N/A',
                'birthday' => null,
                'birthplace' => 'N/A',
                'citizenship' => 'N/A',
                'citizenship_type' => 'N/A',
                'citizenship_country' => 'N/A',
                'gender' => null,
                'tribe' => null,
                'marital_status' => 'N/A',
                'other_status' => 'N/A',
                'religion' => null,
                'disability' => null,
                'specialization' => null,
                'height' => 'N/A',
                'weight' => 'N/A',
                'bloodtype' => 'N/A',
                'gsis_id' => 'N/A',
                'umid_id' => 'N/A',
                'pagibig_id' => 'N/A',
                'philhealth_id' => 'N/A',
                'sss_id' => 'N/A',
                'philsys_id' => 'N/A',
                'tin_no' => 'N/A',
                'agency_emp_no' => 'N/A',
                'add1_lot_no' => 'N/A',
                'add1_street' => 'N/A',
                'add1_sub' => 'N/A',
                'add1_brgy' => 'N/A',
                'add1_city' => 'N/A',
                'add1_prov' => 'N/A',
                'add1_zip' => 'N/A',
                'add2_lot_no' => 'N/A',
                'add2_street' => 'N/A',
                'add2_sub' => 'N/A',
                'add2_brgy' => 'N/A',
                'add2_city' => 'N/A',
                'add2_prov' => 'N/A',
                'add2_zip' => 'N/A',
                'tel_no' => 'N/A',
                'contact' => 'N/A',
                'slug' => null,
                'email' => 'christianjayarponeda02@gmail.com',
                'password' => '$2y$10$HnwkMjQGfV3tRLPA0e2bBOYWD2x/AJn5GZXVkfrEX2j8neYW8ARYe',
                'areacode' => 'IFSU 101',
                'academic_rank' => 'N/A',
                'hep' => 'N/A',
                'hep_course' => null,
                'hep_units' => null,
                'user_access' => null,
                'user_data_man_role' => '4',
                'sias_role' => null,
                'user_role' => '1',
                'user_hr_role' => null,
                'user_dept_role' => null,
                'user_data_role' => null,
                'department' => 16,
                'college' => null,
                'position' => null,
                'parentethical_id' => null,
                'emp_cat' => null,
                'r_status' => null,
                'deactivation_reason' => null,
                'is_approved' => null,
                'validator_comment' => null,
                'account_id' => 1,
                'is_admin' => 1,
                'user_journal_role' => null,
                'remember_token' => '1zBIg6MyJyAEbKvjUgFvZIDYc7bMyXGmqhrLjsjYwK0Kg6a9wDmIWshraS2T',
                'created_at' => '2026-03-09 12:54:28',
                'updated_at' => '2026-04-13 17:25:17',
                'deleted_at' => null,
                'activated_at' => null,
                'last_login' => '2026-04-13 17:25:17',
                'verification_code' => null,
                'verification_created_at' => '2026-04-08 18:25:53',
                'is_requested_vrc' => 'N',
                'password_reset_at' => null,
                'created_user_id' => null,
                'deleted_user_id' => null,
                'activated_user_id' => null,
                'is_project_based' => 'N',
            ],
            // ...other user rows...
        ]);
    }
}
