<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('db_students', function (Blueprint $table) {
            $table->increments('id');
            $table->string('area_code', 15)->nullable();
            $table->string('student_no', 20)->nullable();
            $table->string('last_name', 100)->nullable();
            $table->string('first_name', 100)->nullable();
            $table->string('middle_name', 100)->nullable();
            $table->string('ext_name', 10)->nullable();
            $table->string('gender', 10)->nullable();
            $table->string('civil_status', 15)->nullable();
            $table->string('birth_date', 25)->nullable();
            $table->string('birth_place', 100)->nullable();
            $table->string('citizenship', 50)->nullable();
            $table->string('religion', 50)->nullable();
            $table->string('address', 255)->nullable();
            $table->string('contact_no', 50)->nullable();
            $table->string('email', 100)->nullable();
            $table->string('father', 100)->nullable();
            $table->string('mother', 100)->nullable();
            $table->string('guardian', 100)->nullable();
            $table->string('guardian_contact', 50)->nullable();
            $table->string('school_last_attended', 255)->nullable();
            $table->string('school_last_address', 255)->nullable();
            $table->string('school_last_year', 10)->nullable();
            $table->string('school_last_level', 10)->nullable();
            $table->string('school_last_type', 10)->nullable();
            $table->string('school_last_award', 100)->nullable();
            $table->string('school_last_honor', 100)->nullable();
            $table->string('school_last_gwa', 10)->nullable();
            $table->string('school_last_section', 50)->nullable();
            $table->string('school_last_adviser', 100)->nullable();
            $table->string('school_last_principal', 100)->nullable();
            $table->string('school_last_contact', 50)->nullable();
            $table->string('school_last_email', 100)->nullable();
            $table->string('school_last_remarks', 255)->nullable();
            $table->string('school_last_reason', 255)->nullable();
            $table->string('school_last_transfer', 255)->nullable();
            $table->string('school_last_transfer_date', 25)->nullable();
            $table->string('school_last_transfer_from', 255)->nullable();
            $table->string('school_last_transfer_to', 255)->nullable();
            $table->string('school_last_transfer_reason', 255)->nullable();
            $table->string('school_last_transfer_remarks', 255)->nullable();
            $table->string('school_last_transfer_status', 50)->nullable();
            $table->string('school_last_transfer_type', 50)->nullable();
            $table->string('school_last_transfer_level', 10)->nullable();
            $table->string('school_last_transfer_award', 100)->nullable();
            $table->string('school_last_transfer_honor', 100)->nullable();
            $table->string('school_last_transfer_gwa', 10)->nullable();
            $table->string('school_last_transfer_section', 50)->nullable();
            $table->string('school_last_transfer_adviser', 100)->nullable();
            $table->string('school_last_transfer_principal', 100)->nullable();
            $table->string('school_last_transfer_contact', 50)->nullable();
            $table->string('school_last_transfer_email', 100)->nullable();
            $table->string('school_last_transfer_remarks2', 255)->nullable();
            $table->string('school_last_transfer_reason2', 255)->nullable();
            $table->string('school_last_transfer_status2', 50)->nullable();
            $table->string('school_last_transfer_type2', 50)->nullable();
            $table->string('school_last_transfer_level2', 10)->nullable();
            $table->string('school_last_transfer_award2', 100)->nullable();
            $table->string('school_last_transfer_honor2', 100)->nullable();
            $table->string('school_last_transfer_gwa2', 10)->nullable();
            $table->string('school_last_transfer_section2', 50)->nullable();
            $table->string('school_last_transfer_adviser2', 100)->nullable();
            $table->string('school_last_transfer_principal2', 100)->nullable();
            $table->string('school_last_transfer_contact2', 50)->nullable();
            $table->string('school_last_transfer_email2', 100)->nullable();
            $table->string('school_last_transfer_remarks3', 255)->nullable();
            $table->string('school_last_transfer_reason3', 255)->nullable();
            $table->string('school_last_transfer_status3', 50)->nullable();
            $table->string('school_last_transfer_type3', 50)->nullable();
            $table->string('school_last_transfer_level3', 10)->nullable();
            $table->string('school_last_transfer_award3', 100)->nullable();
            $table->string('school_last_transfer_honor3', 100)->nullable();
            $table->string('school_last_transfer_gwa3', 10)->nullable();
            $table->string('school_last_transfer_section3', 50)->nullable();
            $table->string('school_last_transfer_adviser3', 100)->nullable();
            $table->string('school_last_transfer_principal3', 100)->nullable();
            $table->string('school_last_transfer_contact3', 50)->nullable();
            $table->string('school_last_transfer_email3', 100)->nullable();
            $table->string('school_last_transfer_remarks4', 255)->nullable();
            $table->string('school_last_transfer_reason4', 255)->nullable();
            $table->string('school_last_transfer_status4', 50)->nullable();
            $table->string('school_last_transfer_type4', 50)->nullable();
            $table->string('school_last_transfer_level4', 10)->nullable();
            $table->string('school_last_transfer_award4', 100)->nullable();
            $table->string('school_last_transfer_honor4', 100)->nullable();
            $table->string('school_last_transfer_gwa4', 10)->nullable();
            $table->string('school_last_transfer_section4', 50)->nullable();
            $table->string('school_last_transfer_adviser4', 100)->nullable();
            $table->string('school_last_transfer_principal4', 100)->nullable();
            $table->string('school_last_transfer_contact4', 50)->nullable();
            $table->string('school_last_transfer_email4', 100)->nullable();
            $table->string('school_last_transfer_remarks5', 255)->nullable();
            $table->string('school_last_transfer_reason5', 255)->nullable();
            $table->string('school_last_transfer_status5', 50)->nullable();
            $table->string('school_last_transfer_type5', 50)->nullable();
            $table->string('school_last_transfer_level5', 10)->nullable();
            $table->string('school_last_transfer_award5', 100)->nullable();
            $table->string('school_last_transfer_honor5', 100)->nullable();
            $table->string('school_last_transfer_gwa5', 10)->nullable();
            $table->string('school_last_transfer_section5', 50)->nullable();
            $table->string('school_last_transfer_adviser5', 100)->nullable();
            $table->string('school_last_transfer_principal5', 100)->nullable();
            $table->string('school_last_transfer_contact5', 50)->nullable();
            $table->string('school_last_transfer_email5', 100)->nullable();
            $table->string('is_old_credential_requested', 1)->default('N');
            $table->string('is_agree_terms_conditions', 1)->default('Y');
            $table->string('DSWD_no', 30)->nullable();
            $table->string('prev_school_class', 15)->default('Public');
            $table->string('entrance_data', 500)->nullable();
            $table->string('graduation_date', 25)->nullable();
            $table->string('remember_token', 255)->nullable();
            $table->string('area_transfered_to', 11)->nullable();
            $table->string('area_transfered_from', 11)->nullable();
            $table->timestamp('created_at')->nullable();
            $table->timestamp('emp_created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('emp_updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->timestamp('emp_deleted_at')->nullable();
            $table->timestamp('approved_at')->nullable();
            $table->timestamp('verified_at')->nullable();
            $table->timestamp('activated_at')->nullable();
            $table->timestamp('emp_activated_at')->nullable();
            $table->timestamp('disapproved_at')->nullable();
            $table->timestamp('reactivated_at')->nullable();
            $table->timestamp('transfered_at')->nullable();
            $table->timestamp('requirements_sub_at')->nullable();
            $table->string('verification_code_reset', 6)->nullable();
            $table->timestamp('verification_created_at')->nullable();
            $table->string('is_requested_vrc', 1)->default('N');
            $table->timestamp('password_reset_at')->nullable();
            $table->timestamp('yl_changed_at')->nullable();
            $table->timestamp('admin_changed_password_at')->nullable();
            $table->string('is_codete', 1)->default('N');
            $table->string('is_email_reg_sent', 1)->default('Y');
            $table->string('deactivation_reason', 500)->nullable();
            $table->integer('created_user_id')->nullable();
            $table->integer('emp_created_user_id')->nullable();
            $table->integer('updated_user_id')->nullable();
            $table->integer('emp_updated_user_id')->nullable();
            $table->integer('deleted_user_id')->nullable();
            $table->integer('emp_deleted_user_id')->nullable();
            $table->integer('approved_user_id')->nullable();
            $table->integer('verified_user_id')->nullable();
            $table->integer('activated_user_id')->nullable();
            $table->integer('emp_activated_user_id')->nullable();
            $table->integer('disapproved_user_id')->nullable();
            $table->integer('reactivated_user_id')->nullable();
            $table->integer('transfered_user_id')->nullable();
            $table->integer('yl_changed_user_id')->nullable();
            $table->integer('admin_changed_password_user_id')->nullable();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('db_students');
    }
};
